Bug fix for ClassCastException when using a 'SOAP Mock Response' test step configured with the 'Query/Match' condition
The current implementation of the com.eviware.soapui.impl.support.AbstractMockOperation.setDispatchStyle(String) method will return the old dispatcher object even when it has detected a dispatch style difference and has built a new dispatcher object with the different dispatch style.
This bug causes a ClassCastException to be thrown when using a 'SOAP Mock Response' test step configured with the 'Query/Match' condition on the first run of the Test Case.
This bug can be reproduced with a small update to the existing 'Sample SOAP Project Core' project, as follows:
1) Edit the 'Sample SOAP Project Core' project -> 'Simple TestSuite' test suite -> 'Simple Login and Logout w. Properties Steps' test case and add a new 'SOAP Mock Response' type test step.
2) Configure the new 'SOAP Mock Response' test step with the 'logout' operation of the 'ServiceSoapBinding' interface, with 'Create Response' checked, a suitable port value e.g. 8089 and the path value of '/mockServiceSoapBinding'. Also set the 'Start Step' to the first step in this test case.
3) Update the new 'SOAP Mock Response' test step and configure the 'Query/Match' settings with an 'XPath Query' value of '(string-length(//sessionid) >0)' and the matching value as 'true'
4) Update the 'Test Request - logout' test step and change the endpoint port to match the port of the 'SOAP Mock Response' test step e.g. 8089
5) Start the existing 'ServiceSoapBinding MockService'
6) Run the 'Simple Login and Logout w. Properties Steps' test case
7) The following stack trace is written to the error log:
Tue Jun 05 20:25:02 BST 2018:ERROR:java.lang.ClassCastException: com.eviware.soapui.impl.wsdl.mock.dispatch.SequenceMockOperationDispatcher cannot be cast to com.eviware.soapui.impl.wsdl.mock.dispatch.QueryMatchMockOperationDispatcher
   java.lang.ClassCastException: com.eviware.soapui.impl.wsdl.mock.dispatch.SequenceMockOperationDispatcher cannot be cast to com.eviware.soapui.impl.wsdl.mock.dispatch.QueryMatchMockOperationDispatcher
   	at com.eviware.soapui.impl.wsdl.teststeps.WsdlMockResponseTestStep.initTestMockResponse(WsdlMockResponseTestStep.java:361)
   	at com.eviware.soapui.impl.wsdl.teststeps.WsdlMockResponseTestStep.startListening(WsdlMockResponseTestStep.java:1174)
   	at com.eviware.soapui.impl.wsdl.teststeps.WsdlMockResponseTestStep.access$10(WsdlMockResponseTestStep.java:1168)
   	at com.eviware.soapui.impl.wsdl.teststeps.WsdlMockResponseTestStep$InternalTestRunListener.beforeStep(WsdlMockResponseTestStep.java:1195)
   	at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runBeforeSteps(AbstractTestCaseRunner.java:250)
   	at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runTestStep(AbstractTestCaseRunner.java:208)
   	at com.eviware.soapui.impl.wsdl.testcase.WsdlTestCaseRunner.runCurrentTestStep(WsdlTestCaseRunner.java:47)
   	at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.internalRun(AbstractTestCaseRunner.java:138)
   	at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.internalRun(AbstractTestCaseRunner.java:1)
   	at com.eviware.soapui.impl.wsdl.support.AbstractTestRunner.run(AbstractTestRunner.java:128)
   	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
   	at java.util.concurrent.FutureTask.run(Unknown Source)
   	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   	at java.lang.Thread.run(Unknown Source)

Note: this failure only occurs on the first run of the test case, the correct dispatcher object is returned on any subsequent runs (without a SoapUI application restart) and therefore no class cast exception will be thrown.

This change ensures that the setDispatchStyle() method will return the newly constructed dispatcher object when necessary.